apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service-deployment
spec:
  selector:
    matchLabels:
      app: account-service-pod
  template:
    metadata:
      labels:
        app: account-service-pod
    spec:
      containers:
      - name: account-service-dbless
        image: harbor.skcc-devops.com/nexbank/account-service-dbless:v1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        ports:
        - containerPort: 8081
