apiVersion: v1
kind: Service
metadata:
  name: nexadmin-svc
spec:
  selector: # deployment 의 spec.selector.matchLabels 의 레이블명  app: nexadmin-pod
    app: nexadmin-pod
  ports:
    - name: web
      port: 21611
      protocol: TCP
      targetPort: 21611
    - name: admin
      port: 21612
      protocol: TCP
      targetPort: 21612
  type: ClusterIP
